### PR TITLE
Clean badges

### PR DESCRIPTION
**Pull request by alexhallam**
1. Fixed crates badge link
2. Added a downloads link
3. Removed docs link because it will always show as failed

### CODE REVIEW

**Comment by xliiv** [comment]
> Removed docs link because it will always show as failed

Can you elaborate?

Thank you for your contribution :+1:

**Comment by alexhallam** [comment]
I went to the docs page [https://docs.rs/crate/fui/latest](https://docs.rs/crate/fui/latest) and saw that their was a failure. As long as the failure exists on the docs badge will show a fail. I am not sure what the purpose of the badge for docs is when there are no docs present.

**Comment by xliiv** [comment]
> As long as the failure exists on the docs badge will show a fail.

Let's check if we can fix the error first. Once it's possible the `docs` badge should be kept. :)

**Comment by xliiv** [comment]
> Let's check if we can fix the error first. Once it's possible the `docs` badge should be kept. :)

https://github.com/rust-lang/docs.rs/issues/1744

**Comment by xliiv** [comment]
Thank you for the contribution :+1:

**Pull request merged**
